version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
      - /usr/local/app/node_modules
    working_dir: /usr/local/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
