services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: hugovela1980/hello-world-containerized:6.0
    container_name: hwc-prod-cont
    working_dir: /usr/local/app
    ports:
      - "${HOST_PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - HOST_PORT=${HOST_PORT:-50}
      - LOGGING_URL=${LOGGING_URL}