services:
  app:
    build: .
    image: hugovela1980/hello-world-containerized
    container_name: hwc-dev-cont
    volumes:
      - ./:/usr/local/app
    working_dir: /usr/local/app
    ports:
      - "${HOST_PORT}:${PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - HOST_PORT=${HOST_PORT:-50}
      - LOGGING_URL=${LOGGING_URL}

