services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    image: hugovela1980/hello-world-containerized:latest
    container_name: hwc-dev-cont
    volumes:
      - ./:/usr/local/app
    working_dir: /usr/local/app
    ports:
      - "${HOST_PORT}:${CONT_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - CONT_PORT=${CONT_PORT}
      - HOST_PORT=${HOST_PORT}
      - WELCOME_MESSAGE=Hello World